
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: !secret postgres_url
  purge_keep_days: 365

google_assistant:
  project_id: conquest-smarthome
  service_account: !include SERVICE_KEY.json
  report_state: true
  expose_by_default: false
  entity_config:
    switch.chuveiro: &expose
      expose: true
    switch.interruptor_do_banheiro_l1: *expose
    switch.interruptor_do_banheiro_l2: *expose
    switch.interruptor_do_banheiro_l3: *expose
    switch.interruptor_da_cozinha_l1: *expose
    switch.interruptor_central_l1: *expose
    switch.interruptor_central_l2: *expose
    switch.interruptor_central_l3: *expose
    switch.interruptor_da_entrada_l1: *expose
    script.desligar_todas_as_luzes: *expose
    script.ligar_luzes_principais: *expose
    

alexa:
  smart_home:
    filter:
      include_entities:
        - switch.chuveiro
        - switch.interruptor_do_banheiro_l1
        - switch.interruptor_do_banheiro_l2
        - switch.interruptor_do_banheiro_l3
        - switch.interruptor_da_cozinha_l1
        - switch.interruptor_central_l1
        - switch.interruptor_central_l2
        - switch.interruptor_central_l3
        - switch.interruptor_da_entrada_l1
        - script.desligar_todas_as_luzes
        - script.ligar_luzes_principais
        
